apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1

    spec:
      containers:
        - name: app-1
          image: chineidu/other_service:v1.1
          imagePullPolicy: IfNotPresent # default
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 6060
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secret # from secrets.metadata.mane
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: password
            - name: HOSTNAME
              value: "mongo-service.development" # "service-name.namespace"
