apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: first-app
  template:
    metadata:
      labels:
        app: first-app
    spec:
      containers:
        - name: first-app
          image: chineidu/mlops:v3
          imagePullPolicy: IfNotPresent # default
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
