apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second-app
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: second-app
  template:
    metadata:
      labels:
        app: second-app
    spec:
      containers:
        - name: second-app
          image: chineidu/mlops:v3
          imagePullPolicy: IfNotPresent # default
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            periodSeconds: 10
            initialDelaySeconds: 5
          ports:
            - containerPort: 8000
