apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: development
type: Opaque
data:
  mongo_initdb_root_username: bmVpZHU=
  mongo_initdb_root_password: cGFzc3dvcmQ=
stringData:
  username: neidu
  password: password
  # hostname: 10.100.147.172
