version: "3.8"

services:
  mlflow-db: # 1st service
    image: postgres:16-bullseye
    container_name: mlflow-backend-store # Also used as hostname
    env_file: # Location of file(s) containing the env vars
    - ./envs/.postgres

  mlflow-server: # 2nd service
    image: local-mlflow-tracking-server
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        MLFLOW_ARTIFACTS_STORE: ${MLFLOW_ARTIFACTS_STORE}
    container_name: local-mlflow-tracking-server
    ports:
      - ${LOCAL_DEV_MLFLOW_SERVER_PORT}:${LOCAL_DEV_MLFLOW_SERVER_PORT}
    depends_on:
      - mlflow-db
    env_file:
      - ./envs/.postgres
      - ./envs/.mlflow-prod
      - ./envs/.mlflow-dev
    volumes:
      - ./:/app
      - artifacts-store:/${MLFLOW_ARTIFACTS_STORE} # Named volume
    ipc: host


  mongodb:
    image: mongo:7.0-rc
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=neidu
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - data:/data/db # Named volume

# Named volumes ONLY!
volumes:
  postgresql-data:
  artifacts-store:
