# For local debugging and testing!
version: "3.8"

services:
 app: &app # 1st service
    user: root # Run as the root user
    hostname: ${HOSTNAME}
    image: ${DOCKER_IMAGE_NAME}
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.prod
    container_name: mlflow-tracking-server
    ports:
      - ${MLFLOW_PORT}:${MLFLOW_PORT}
    env_file:
      - ./.envs/.mlflow.prod
    volumes:
      - ./:/app
    ipc: host
    network_mode: host
