# Specify the default (important!)
defaults:
  - experiment: exp-with-resnet18
  - loss_function: mseLoss
  - experiment@neidu: exp-with-resnet50
  - _self_ # Every object/key below it becomes the default


experiment:
  optimizer:
    name: sgd
