# Specify the default (important!)
defaults:
  - experiment: exp-with-resnet18
  - loss_function: mseLoss
  - _self_ # Every object/key below it becomes the defaulr

experiment:
  optimizer:
    name: sgd
