name: Reusable Workflow
on:
  workflow_call:
    inputs:
        username:
            description: 'The name of the developer running the job'
            default: 'dev-account'
            required: false
            type: string
    secrets:
      DB_NAME:
        required: false


jobs:
  deploy:
      runs-on: ubuntu-latest

      steps:
          - name: Output Information
            run: |
              echo "developer: ${{ inputs.username}}"
              echo "developer: ${{ secrets.DB_NAME}}"
              echo "Deploying to prod ..."
