name: Reusable Workflow
on:
  workflow_call:

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
          - name: Output Information
            run: |
              echo "Deploying to prod ..."
