name: Setup Poetry

on:  # trigger(s)
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build:  # Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4

      - name: Pytbon Setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: Gr1N/setup-poetry@v8

      - name: Poetry Setup
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Verify Poetry Setup
        run: pip list

      - name: Run Code
        run: |
          cd my-app
          poetry run python main.py


  deploy: # Job 2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Pytbon Setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Deploy Code
        run: |
          echo "Deploying ... "
