name: Workflow 1  # name of the workflow

on:  # trigger(s)
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build: # name of the job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4  # action

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |  # script
          echo ">>> Installing dependencies ... <<<"
          pip install rich typeguard

      - name: Example Code
        run: |
          echo ">>> Running ... <<<"
          python other_notes/Python_classes_notes/src/main.py
